# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

language: python

sudo: true

python:
  - 2.7
  - 3.5

cache: pip

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

build:
  ci:
    - echo $CI_REPORTS && mkdir -p $CI_REPORTS
    - echo $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS

before_install:
#  - mkdir gco_source
  - pip install --upgrade pip
#  - apt-get install freetype*

install:
  - pip install -r requirements.txt
  - pip install pytest>=3.1.3 coverage codecov nose

#  - make download  # the download site is down
  - make all
  - make rm

  - python setup.py build_ext --inplace

script:
  - nosetests test_examples.py --with-xunit --xunit-file=$CI_REPORTS/nosetests.xml
  - nosetests gco test_examples.py --exe -v  --with-xunit --with-doctest --with-coverage --cover-package gco

after_success:
  - codecov --token=1aef0194-048a-4c59-a0d1-9408b924c493
  - coverage xml -o $COVERAGE_REPORTS/coverage.xml
  - coverage report

  # test running after installation
  - python setup.py install
  - rm -f -r gco
  - python test_examples.py
