# https://www.appveyor.com/docs/appveyor-yml/
environment:

  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"


install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%path%
  - python --version
  - pip --version
  - pip install -r requirements.txt
  - pip install pytest  # nose coverage
  - pip list

build_script:
  # Build the compiled extension
  # - nmake -f Makefile download
  # - nmake -f Makefile all
  # - nmake -f Makefile test_wrapper
  - python setup.py build_ext --inplace
  # - python setup.py install
  - dir

test_script:
  - pytest --doctest-modules
#  - nosetests --with-coverage   # --cover-package=pygco

on_success:
  - coverage report